---
- hosts: all
  become: yes
  remote_user: vagrant

  tasks:
  - name: Ensure chrony (for time synchronization) is installed.
    yum:
      name: ntp
      state: present

  - name: Ensure chrony is running.
    service:
      name: chronyd
      state: started
      enabled: yes
